version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/myApp/staticfiles
      - media_volume:/myApp/media
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13-alpine3.14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/myApp/staticfiles
      - media_volume:/myApp/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: