# Generated by Django 4.0.1 on 2022-02-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_client.base')),
                ('image', models.ImageField(upload_to='')),
                ('name_business', models.CharField(max_length=100)),
                ('money_min', models.IntegerField()),
                ('profit_year', models.IntegerField()),
                ('profit_month', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('text_min', models.TextField(max_length=100)),
            ],
            bases=('web_client.base',),
        ),
    ]
